### ISSUE TITLE
Request for permission to adapt the idea for this project for school projects

### ISSUE THREAD

**Issue by dalelane** [sta-ger/HalfBeer#1]
I run https://machinelearningforkids.co.uk/ - a set of free resources for schools to teach children about ML. I love the idea behind this project and think it would make a great school class activity. 

Would you mind if I wrote a school worksheet based on the idea, please? 

I would naturally be happy to credit you as the original source of the idea for the activity, with whatever credit/attribution/links you'd like.

Thanks for your consideration

**Comment by sta-ger** [comment]
Hi, great idea! Without any doubts you can use this project for your purposes. (:

**Comment by dalelane** [comment]
Thank you so much - that's very kind!

https://twitter.com/MLforKids/status/1311769704818774016
